# Build settings

markdown: kramdown
permalink: pretty

port: 80
host: 127.0.0.1
baseurl: "http://ammocan.github.io" # does not include hostname

include: ['_includes/work']
exclude: []
keep_files: ['.html']

sass:
  sass_dir: assets/css
  style: :nested
