#-------------------------------
# General Site Settings

title: AMMOCAN
description: Designer ✪ Coder ✪ Veteran
email: ammo@2-Drops.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Scoop, url: '#scoop'}
- {name: Creations, url: '#creations'}
- {name: Kudos, url: '#kudos'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'AMMOCAN is a web designer, coder and veteran in Baltimore, MD.'
  rel-author: 'https://plus.google.com/u/0/+ammocan/'
  rel-publisher: 'https://plus.google.com/u/0/+ammocan/'

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **AMMOCAN specializes in dropping creativity** back into technology.
  Most of the things he creates are [more than meets the eye](http://www.2-Drops.com),
  but he also puts great effort into assisting fellow [vetrepreneurs](http://vet-tech.us)
  and creating [YouTube tutorials](http://youtube.com/user/2DropsVlog) on ways to be a better web citizen.


skills:
- {name: Passion, value: '10'}
- {name: Problem Solving, value: '9'}
- {name: Communication, value: '8'}
- {name: Diversity, value: '8'}
- {name: Discipline, value: '9'}
- {name: Efficiency, value: '8'}
- {name: Learning, value: '10'}
- {name: Responsibility, value: '9'}

#-------------------------------
# Work Section

projects:
- {name: Creation - 1, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Creation - 2, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Creation - 3, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Creation - 4, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Creation - 5, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Creation - 6, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Creation - 7, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Creation - 8, folder: 'proj-8', file: 'work/proj-8.html'}

#-------------------------------
# Clients Section

clients:
- {avatar: 'face-ryan.jpg', name: 'Ryan Micheletti', title: 'Director of Operations, Vet-Tech', quote: '<p><strong>AMMO is an excellent designer and developer</strong>. He has greatly helped Vet-Tech by creating an Infographic and implementing several website edits. He is now our "go to" person for website and design projects.</p>', logo: 'logo1.png'}
- {avatar: 'face-jay.jpg', name: 'Jay Neighbors', title: 'Creative Director, ignition72', quote: '<p><strong>Working with AMMOCAN was a pleasure</strong>, he has a great work ethic and eye for subtle details. He can handle anything you throw at him plus is a joy to work with, great sense of humor and excellent team player.</p>', logo: 'logo2.jpg'}
- {avatar: 'face-matt.jpg', name: 'Matt McDermott', title: 'Creative Director, idfive', quote: '<p><strong>AMMO is a passionate professional</strong>, who understands the value of loyalty and flexibility. While at idfive, he gladly took on any role that we asked of him—a rare thing in an age of self-entitlement and prima donna complexes. From development and research to writing and design, he tackled each with enthusiasm. Articulate and energetic, he has a great deal of potential—and a genuine desire to live up to it. His outgoing personality was a welcome addition to the idfive culture.</p>', logo: 'logo3.png'}
- {avatar: 'face-steve.jpg', name: 'Steven Stephenson', title: 'Sr. Web Developer, idfive', quote: '<p><strong>AMMOCAN is a very passionate guy</strong>, who cares about his craft. He is extremely hard working, friendly and has enough enthusiasm to fill a stadium. Working with him has been a pleasure and hopefully down the line we will work together again.</p>', logo: 'logo4.png'}
  
  
#-------------------------------
# Contact Section
  
social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}

  
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
  
  
  
  
  
  
